### ISSUE TITLE
SNOW-878027: snowflake-cli-labs 1.0.0 is not working

### ISSUE THREAD

**Issue by sfc-gh-cheliu** [Snowflake-Labs/snowcli#272]
### Python version

3.8

### Platform

MacOS M2 MAX

### What happened

When creating new (custom) packages using
`When creating new (custom) packages using`
Got the following error:
`Traceback (most recent call last):
  File "/Users/cheliu/anaconda3/bin/snow", line 5, in <module>
    from snowcli.cli import app
  File "/Users/cheliu/anaconda3/lib/python3.10/site-packages/snowcli/cli/__init__.py", line 11, in <module>
    from snowcli.cli import (
  File "/Users/cheliu/anaconda3/lib/python3.10/site-packages/snowcli/cli/connection.py", line 8, in <module>
    from snowcli.cli.common.flags import DEFAULT_CONTEXT_SETTINGS
  File "/Users/cheliu/anaconda3/lib/python3.10/site-packages/snowcli/cli/common/flags.py", line 4, in <module>
    from snowcli.utils import check_for_connection
  File "/Users/cheliu/anaconda3/lib/python3.10/site-packages/snowcli/utils.py", line 24, in <module>
    from snowcli.config import cli_config
  File "/Users/cheliu/anaconda3/lib/python3.10/site-packages/snowcli/config.py", line 14, in <module>
    from snowflake.connector.constants import CONFIG_FILE
ImportError: cannot import name 'CONFIG_FILE' from 'snowflake.connector.constants' (/Users/cheliu/anaconda3/lib/python3.10/site-packages/snowflake/connector/constants.py)`

**Comment by sfc-gh-turbaszek** [comment]
Please install `snowflake-connector-python-nightly[secure-local-storage]==2023.6.24` as snowcli rely on unreleased version of connector.

**Comment by sfc-gh-cheliu** [comment]
@sfc-gh-turbaszek Thanks! Just to confirm, the custom package won't work if it contains non-Python code, is my understanding correct?
