### ISSUE TITLE
SNOW-880471: snow snowpark procedure init requirements should include toml for local test

### ISSUE THREAD

**Issue by sfc-gh-cconner** [Snowflake-Labs/snowcli#282]
### Python version

Python 3.8.13

### Platform

macOS-13.4.1-arm64-arm-64bit

### What happened

Ran the following:

`snow snowpark procedure init
pip install -r requirements.txt
python app.py`

Should have resulted in a successful test, but instead failed because toml wasn't included as a dependency in the requirements.txt.

### Console output

```Shell
`❯ python app.py
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from snowflake.snowpark import Session
  File "/Users/cconner/.pyenv/versions/t00557154/lib/python3.8/site-packages/snowflake/snowpark/__init__.py", line 46, in <module>
    from snowflake.snowpark.async_job import AsyncJob
  File "/Users/cconner/.pyenv/versions/t00557154/lib/python3.8/site-packages/snowflake/snowpark/async_job.py", line 10, in <module>
    from snowflake.connector.options import pandas
  File "/Users/cconner/.pyenv/versions/t00557154/lib/python3.8/site-packages/snowflake/connector/__init__.py", line 17, in <module>
    from .connection import SnowflakeConnection
  File "/Users/cconner/.pyenv/versions/t00557154/lib/python3.8/site-packages/snowflake/connector/connection.py", line 44, in <module>
    from .config_manager import CONFIG_PARSER
  File "/Users/cconner/.pyenv/versions/t00557154/lib/python3.8/site-packages/snowflake/connector/config_manager.py", line 17, in <module>
    import tomlkit
ModuleNotFoundError: No module named 'tomlkit'`
```

### How to reproduce

Install snowcli 1.0.1 and run:

`snow snowpark procedure init
pip install -r requirements.txt
python app.py`

**Comment by sfc-gh-cconner** [comment]
https://github.com/sfc-gh-cconner/snowcli/pull/new/add_toml_to_requirements
